namespace Theater.MlbDataServer
{
	export class Teams
	{
		public static TeamList: { [filecode: string]: string } =
		{
			"ari": "Arizona Diamondbacks",
			"atl": "Atlanta Braves",
			"bal": "Baltimore Orioles",
			"bos": "Boston Red Sox",
			"chc": "Chicago Cubs",
			"cws": "Chicago White Sox",
			"cin": "Cincinnati Reds",
			"cle": "Cleveland Indians",
			"col": "Colorado Rockies",
			"det": "Detroit Tigers",
			"mia": "Miami Marlins",
			"hou": "Houston Astros",
			"kc": "Kansas City Royals",
			"laa": "Los Angeles Angels",
			"la": "Los Angeles Dodgers",
			"mil": "Milwaukee Brewers",
			"min": "Minnesota Twins",
			"nym": "New York Mets",
			"nyy": "New York Yankees",
			"oak": "Oakland Athletics",
			"phi": "Philadelphia Phillies",
			"pit": "Pittsburgh Pirates",
			"sd": "San Diego Padres",
			"sf": "San Francisco Giants",
			"sea": "Seattle Mariners",
			"stl": "St. Louis Cardinals",
			"tb": "Tampa Bay Rays",
			"tex": "Texas Rangers",
			"tor": "Toronto Blue Jays",
			"was": "Washington Nationals"
		}

		public static TeamIdList: { [teamId: number]: string } = {
			108: "laa",
			109: "ari",
			110: "bal",
			111: "bos",
			112: "chc",
			113: "cin",
			114: "cle",
			115: "col",
			116: "det",
			117: "hou",
			118: "kc",
			119: "la",
			120: "was",
			121: "nym",
			133: "oak",
			134: "pit",
			135: "sd",
			136: "sea",
			137: "sf",
			138: "stl",
			139: "tb",
			140: "tex",
			141: "tor",
			142: "min",
			143: "phi",
			144: "atl",
			145: "chw",
			146: "mia",
			147: "nyy",
			158: "mil",
		}
	}
}